// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD3b9yXwzdOn7lanzgQBZ-9OQ2ldbpEfg',
    appId: '1:690348610788:web:c42b5b313310b67f8388f1',
    messagingSenderId: '690348610788',
    projectId: 'flutter-chat-app-4cf22',
    authDomain: 'flutter-chat-app-4cf22.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4cf22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3qhVqu7jxS76VpNbT52ajLh4XJncQrI',
    appId: '1:690348610788:android:b212462262e894a28388f1',
    messagingSenderId: '690348610788',
    projectId: 'flutter-chat-app-4cf22',
    storageBucket: 'flutter-chat-app-4cf22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_iP3NyQDH7_cH1gQtZSSWLR511Io2vE',
    appId: '1:690348610788:ios:5e8f660b6443c3358388f1',
    messagingSenderId: '690348610788',
    projectId: 'flutter-chat-app-4cf22',
    storageBucket: 'flutter-chat-app-4cf22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_iP3NyQDH7_cH1gQtZSSWLR511Io2vE',
    appId: '1:690348610788:ios:5e8f660b6443c3358388f1',
    messagingSenderId: '690348610788',
    projectId: 'flutter-chat-app-4cf22',
    storageBucket: 'flutter-chat-app-4cf22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD3b9yXwzdOn7lanzgQBZ-9OQ2ldbpEfg',
    appId: '1:690348610788:web:c65fec6419bd18188388f1',
    messagingSenderId: '690348610788',
    projectId: 'flutter-chat-app-4cf22',
    authDomain: 'flutter-chat-app-4cf22.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4cf22.firebasestorage.app',
  );

}